# -*- python -*-
import os, sys
Import('env libhammer_shared testruns targets')

javaenv = env.Clone()
javaenv['ENV']['LD_LIBRARY_PATH'] = os.path.dirname(str(libhammer_shared[0]))

def PrependDir(dir, filelist):
    return [os.path.join(dir,x) for x in filelist]

csources = [
    "com_upstandinghackers_hammer_Hammer.c",
    "com_upstandinghackers_hammer_ParsedToken.c",
    "com_upstandinghackers_hammer_Parser.c",
    "com_upstandinghackers_hammer_ParseResult.c"   
]

classes = javaenv.Java(target = 'classes', source = '#src/bindings/java/jsrc')
jni_headers = javaenv.JavaH(target = 'csrc', source = classes)

native_src = PrependDir('csrc', csources)
libhammer_java = javaenv.SharedLibrary('libjhammer', [native_src, libhammer_shared])
Default(libhammer_java)