# -*- python -*-
Import("env libhammer_shared")

cppenv = env.Clone()
cppenv.Append(CPPPATH=[".", "vendor/gtest-1.7.0/fused-src", "../.."])
cppenv.MergeFlags("-Wno-missing-field-initializers -DGTEST_HAS_PTHREAD=0")


gtest = cppenv.Object("vendor/gtest-1.7.0/fused-src/gtest/gtest-all.cc")


hammer_test = cppenv.Program("hammer_test", libhammer_shared + gtest + ['cpp_tests.cpp'])

